skills_list = [
    "python",
    "java",
    "c programming",
    "c++",
    "javascript",
    "html",
    "css",
    "sql",
    "mysql",
    "mongodb",
    "data structures",
    "algorithms",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data analysis",
    "data visualization",
    "power bi",
    "tableau",
    "excel",
    "nlp",
    "computer vision",
    "flask",
    "django",
    "react",
    "node js",
    "git",
    "github",
    "linux",
    "api development",
    "cloud computing",
    "aws",
    "azure",
    "cybersecurity",
    "networking",
    "debugging",
    "problem solving",
    "communication",
    "teamwork",
    "time management"
]